import express from 'express';
import path from 'path';
import fs from 'fs';
import dotenv from 'dotenv';
import { createServer as createViteServer } from 'vite';

dotenv.config();
const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = path.join(process.cwd(), 'data');
const STORE_PATH = path.join(DATA_DIR, 'store.json');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

type Monitor = { id:string; name:string; prompt:string; subreddits:string[]; enabled:boolean; threshold:number; createdAt:string };
type Match = { id:string; monitorId:string; monitorName:string; title:string; text:string; subreddit:string; author:string; url:string; createdAt:string; score:number; relevance:number; intent:string; alerted:boolean };
type Store = { monitors:Monitor[]; matches:Match[]; lastPoll:string|null; settings:{ slackWebhook:string; pollInterval:number } };
const defaults:Monitor[]=[{id:'m1',name:'Brand mentions',prompt:'Find posts or comments that mention Nimbata.',subreddits:['all'],enabled:true,threshold:65,createdAt:new Date().toISOString()},{id:'m2',name:'CallRail complaints',prompt:'Find people complaining about CallRail or looking for a CallRail alternative.',subreddits:['PPC','marketing','agency'],enabled:true,threshold:75,createdAt:new Date().toISOString()},{id:'m3',name:'Call tracking intent',prompt:'Find people asking for recommendations or help choosing call tracking software.',subreddits:['PPC','GoogleAds','marketing'],enabled:true,threshold:70,createdAt:new Date().toISOString()}];
function save(s:Store){fs.writeFileSync(STORE_PATH,JSON.stringify(s,null,2))} function load():Store{try{if(fs.existsSync(STORE_PATH))return JSON.parse(fs.readFileSync(STORE_PATH,'utf8'))}catch(e){console.error(e)}const s:Store={monitors:defaults,matches:[],lastPoll:null,settings:{slackWebhook:process.env.SLACK_WEBHOOK_URL||'',pollInterval:1}};save(s);return s} function uid(p='x'){return p+'_'+Math.random().toString(36).slice(2)+Date.now().toString(36)}
function terms(prompt:string){const stop=new Set(['find','posts','comments','mention','mentions','people','complaining','complain','asking','ask','looking','for','reddit','conversations','where','that','about','or','and','the','with','who','what','are','is','best','this','software']);return prompt.replace(/[^a-zA-Z0-9\s-]/g,' ').split(/\s+/).filter(x=>x.length>3&&!stop.has(x.toLowerCase())).slice(0,12)}
function relevance(text:string,prompt:string){const lower=text.toLowerCase();const p=terms(prompt);const hits=p.filter(x=>lower.includes(x.toLowerCase())).length;return Math.min(98,Math.max(20,Math.round(45+(hits/Math.max(1,p.length))*55)))} function intent(text:string){const t=text.toLowerCase();if(/alternative|recommend|best|looking for|switch|should i use/.test(t))return'Buying intent';if(/complain|hate|bad|issue|problem|expensive|frustrat/.test(t))return'Pain point';if(/what is|how do|how can/.test(t))return'Question';return'Mention'}
async function fetchRedditRss(subreddit:string,limit=50){const name=subreddit.replace(/^r\//i,'').trim();const url=`https://www.reddit.com/r/${encodeURIComponent(name)}/new/.rss?limit=${limit}`;const r=await fetch(url,{headers:{'User-Agent':process.env.REDDIT_USER_AGENT||'RedditListening/1.0'}});if(!r.ok)throw new Error(`Reddit RSS returned ${r.status}`);const xml=await r.text();return[...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(x=>{const entry=x[1];const get=(tag:string)=>entry.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i'))?.[1]?.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim()||'';return{title:get('title'),content:get('content'),author:get('name'),updated:get('updated'),url:entry.match(/<link[^>]+href="([^"]+)"/i)?.[1]||''}})}
async function poll(s:Store){const out:Match[]=[];for(const m of s.monitors.filter(x=>x.enabled)){for(const sub of (m.subreddits.length?m.subreddits:['all'])){try{const entries=await fetchRedditRss(sub==='all'?'popular':sub);for(const d of entries){const text=[d.title,d.content].filter(Boolean).join(' '),rel=relevance(text,m.prompt);if(rel<m.threshold||!d.url||s.matches.some(x=>x.url===d.url&&x.monitorId===m.id))continue;out.push({id:uid('match'),monitorId:m.id,monitorName:m.name,title:d.title||'(Reddit post)',text:d.content.slice(0,700),subreddit:sub,author:d.author||'unknown',url:d.url,createdAt:d.updated||new Date().toISOString(),score:0,relevance:rel,intent:intent(text),alerted:false})}}catch(e){console.error(e)}}}return out}
async function slack(url:string,m:Match){if(!url)return false;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:`*🔥 Reddit match — ${m.monitorName}*\n*r/${m.subreddit}* · ${m.relevance}% relevance · ${m.intent}\n\n*${m.title}*\n${m.text.slice(0,700)}\n\n<${m.url}|View on Reddit>`})});return r.ok}
function demo(s:Store){[['CallRail alternative for small agencies','I have been using CallRail but the reporting is getting expensive. What alternatives are people using?','PPC','CallRail complaints',92,'Buying intent'],['How are you tracking phone leads from Google Ads?','Looking for a reliable way to know which Google Ads campaigns actually generate phone calls.','GoogleAds','Call tracking intent',88,'Question'],['Nimbata review?','Has anyone here tried Nimbata for call tracking? Curious about attribution and reporting.','agency','Brand mentions',96,'Mention']].forEach((e,i)=>{const m=s.monitors.find(x=>x.name===e[3]);if(!m)return;const u=`https://www.reddit.com/r/${e[2]}/comments/demo${i}`;if(s.matches.some(x=>x.url===u))return;s.matches.unshift({id:uid('match'),monitorId:m.id,monitorName:m.name,title:e[0]as string,text:e[1]as string,subreddit:e[2]as string,author:'demo_user',url:u,createdAt:new Date(Date.now()-i*60000).toISOString(),score:24-i*5,relevance:e[4]as number,intent:e[5]as string,alerted:false})})}
const app=express();app.use(express.json());app.get('/api/data',(req,res)=>{const s=load();res.json({monitors:s.monitors,matches:s.matches.slice(0,100),stats:{matches24h:s.matches.filter(m=>Date.now()-new Date(m.createdAt).getTime()<86400000).length,alerts24h:s.matches.filter(m=>m.alerted&&Date.now()-new Date(m.createdAt).getTime()<86400000).length,monitors:s.monitors.length,lastPoll:s.lastPoll},settings:{slackConfigured:Boolean(s.settings.slackWebhook||process.env.SLACK_WEBHOOK_URL),redditConfigured:true,pollInterval:s.settings.pollInterval}})});app.post('/api/monitors',(req,res)=>{const{name,prompt,subreddits=['all'],threshold=70}=req.body;if(!name||!prompt)return res.status(400).json({error:'name and prompt are required'});const s=load(),m:Monitor={id:uid('mon'),name:String(name).trim(),prompt:String(prompt).trim(),subreddits:Array.isArray(subreddits)&&subreddits.length?subreddits.map(String):['all'],enabled:true,threshold:Number(threshold),createdAt:new Date().toISOString()};s.monitors.unshift(m);save(s);res.json(m)});app.patch('/api/monitors/:id',(req,res)=>{const s=load(),m=s.monitors.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({error:'not found'});if(typeof req.body.enabled==='boolean')m.enabled=req.body.enabled;save(s);res.json(m)});app.post('/api/settings',(req,res)=>{const s=load();if(typeof req.body.slackWebhook==='string')s.settings.slackWebhook=req.body.slackWebhook.trim();save(s);res.json({success:true})});app.post('/api/demo',(req,res)=>{const s=load();demo(s);save(s);res.json({success:true})});app.post('/api/poll',async(req,res)=>{if(process.env.POLL_SECRET&&req.header('x-poll-secret')!==process.env.POLL_SECRET)return res.status(401).json({error:'Unauthorized'});const s=load();try{const matches=await poll(s);let alerts=0;for(const m of matches){s.matches.unshift(m);m.alerted=await slack(s.settings.slackWebhook||process.env.SLACK_WEBHOOK_URL||'',m);if(m.alerted)alerts++}s.lastPoll=new Date().toISOString();s.matches=s.matches.slice(0,1000);save(s);res.json({success:true,matches:matches.length,alerts,lastPoll:s.lastPoll})}catch(e:any){s.lastPoll=new Date().toISOString();save(s);res.status(500).json({error:e?.message||'Polling failed'})}});app.get('/api/health',(req,res)=>res.json({ok:true}));
async function start(){const prod=process.env.NODE_ENV==='production';if(!prod){const vite=await createViteServer({server:{middlewareMode:true,host:'0.0.0.0'},appType:'spa'});app.use(vite.middlewares)}else{app.use(express.static(path.join(process.cwd(),'dist')));app.get('*',(req,res)=>res.sendFile(path.join(process.cwd(),'dist','index.html')))}app.listen(PORT,()=>console.log(`Reddit Listening running on http://localhost:${PORT}`))}start().catch(err=>{console.error(err);process.exit(1)});
