import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,Bell,CheckCircle2,ChevronDown,ChevronRight,Clock3,ExternalLink,Filter,Hash,MessageSquare,Pause,Play,Plus,Radio,Search,Settings,ShieldCheck,Sparkles,X,Trash2}from'lucide-react';
import'./styles.css';

type Rule={id:string;value:string};
type Monitor={id:string;name:string;description:string;all:Rule[];any:Rule[];exclude:Rule[];subreddits:string[];enabled:boolean;threshold:number;createdAt:string};
type Match={id:string;monitorId:string;monitorName:string;title:string;text:string;subreddit:string;author:string;url:string;createdAt:string;score:number;relevance:number;intent:string;alerted:boolean};
type Data={monitors:Monitor[];matches:Match[];stats:{matches24h:number;alerts24h:number;monitors:number;lastPoll:string|null;pollError:string|null};settings:{slackConfigured:boolean;redditConfigured:boolean;source:string;pollInterval:number}};

type RuleMode='all'|'any'|'exclude';
const emptyRules=()=>({all:[],any:[],exclude:[]});

function App(){
 const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState<'activity'|'monitors'|'settings'>('activity');const[modal,setModal]=useState(false);const[q,setQ]=useState('');const[filter,setFilter]=useState<'all'|'unread'|'buying'|'pain'|'question'>('all');const[busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await fetch('/api/data');if(r.ok)setData(await r.json())}catch{}};
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 const filtered=useMemo(()=>data?.matches.filter(m=>{const search=(m.title+' '+m.text+' '+m.subreddit+' '+m.monitorName).toLowerCase();const qok=!q||search.includes(q.toLowerCase());const fok=filter==='all'||filter==='unread'&&!m.alerted||filter==='buying'&&m.intent==='Buying intent'||filter==='pain'&&m.intent==='Pain point'||filter==='question'&&m.intent==='Question';return qok&&fok})||[],[data,q,filter]);
 const demo=async()=>{setBusy(true);await fetch('/api/poll',{method:'POST'});await load();setBusy(false)};
 if(!data)return <div className="loading"><Radio/>Loading…</div>;
 return <div className="app"><aside><div className="logo"><div className="logoMark"><Radio size={18}/></div><div><b>Reddit Listening</b><span>Social intelligence</span></div></div><nav><button className={tab==='activity'?'active':''}onClick={()=>setTab('activity')}><Activity/>Live activity</button><button className={tab==='monitors'?'active':''}onClick={()=>setTab('monitors')}><Search/>Monitors<em>{data.monitors.length}</em></button><button className={tab==='settings'?'active':''}onClick={()=>setTab('settings')}><Settings/>Settings</button></nav><div className="sideBottom"><div className="status"><span></span><div><b>Reddit scan active</b><small>{data.stats.lastPoll?'Last scan '+ago(data.stats.lastPoll):'Starting scanner…'}</small></div></div><button className="demo"onClick={demo}><Sparkles/>{busy?'Scanning…':'Scan now'}</button></div></aside><main>
 <header><div><p className="eyebrow">REDDIT / LISTENING</p><h1>{tab==='activity'?'Live activity':tab==='monitors'?'Monitors':'Settings'}</h1><p className="sub">{tab==='activity'?'New Reddit conversations matched by your monitors.':tab==='monitors'?'Create keyword monitors with AND, OR and NOT logic.':'Configure alerts and monitoring.'}</p></div>{tab==='monitors'&&<button className="primary"onClick={()=>setModal(true)}><Plus/>New monitor</button>}</header>
 {tab==='activity'&&<><div className="stats"><Stat icon={<MessageSquare/>}label="Matches · 24h"value={data.stats.matches24h}/><Stat icon={<Bell/>}label="Slack alerts · 24h"value={data.stats.alerts24h}/><Stat icon={<Radio/>}label="Active monitors"value={data.monitors.filter(m=>m.enabled).length}/><Stat icon={<Clock3/>}label="Scanning"value={data.settings.pollInterval+' min'}/></div><div className="toolbar"><div className="search"><Search/><input placeholder="Search matches…"value={q}onChange={e=>setQ(e.target.value)}/></div><div className="filterWrap"><button className="filter"onClick={()=>setFilter(filter==='all'?'unread':'all')}><Filter/> {filter==='all'?'All matches':filter==='unread'?'Not alerted':filter==='buying'?'Buying intent':filter==='pain'?'Pain points':'Questions'}<ChevronDown/></button><div className="filterMenu"><button onClick={()=>setFilter('all')}>All matches</button><button onClick={()=>setFilter('unread')}>Not alerted</button><button onClick={()=>setFilter('buying')}>Buying intent</button><button onClick={()=>setFilter('pain')}>Pain points</button><button onClick={()=>setFilter('question')}>Questions</button></div></div></div>{data.stats.pollError&&<div className="error">Scanner error: {data.stats.pollError}</div>}<section className="feed">{filtered.length?filtered.map(m=><MatchCard key={m.id}match={m}/>):<Empty onScan={demo}/>}</section></>}
 {tab==='monitors'&&<MonitorList monitors={data.monitors}reload={load}create={()=>setModal(true)}/>}{tab==='settings'&&<SettingsPanel data={data}reload={load}/>}</main>{modal&&<CreateModal close={()=>setModal(false)}created={()=>{setModal(false);load()}}/>}</div>;
}
function Stat(p:{icon:React.ReactNode;label:string;value:any}){return <div className="stat"><div className="statIcon">{p.icon}</div><div><small>{p.label}</small><strong>{p.value}</strong></div></div>}
function MatchCard({match:m}:{match:Match}){return <article className="match"><div className="matchTop"><div className="source"><span className="redditDot">●</span><b>r/{m.subreddit}</b><span>·</span>{ago(m.createdAt)}</div><span className={'intent '+(m.relevance>=80?'hot':'')}>{m.intent}</span></div><h3>{m.title}</h3><p>{m.text}</p><div className="matchBottom"><span className="monitorTag"><Hash/>{m.monitorName}</span><span>{m.relevance}% match</span><a href={m.url}target="_blank"rel="noreferrer">View on Reddit <ExternalLink/></a><span className={m.alerted?'alertSent':'alertPending'}>{m.alerted?<><CheckCircle2/>Slack sent</>:<><Bell/>Not alerted</>}</span></div></article>}
function Empty({onScan}:{onScan:()=>void}){return <div className="empty"><div className="emptyIcon"><Radio/></div><h2>No matches yet</h2><p>The scanner is checking Reddit continuously. Create a monitor or run a scan now.</p><button className="primary"onClick={onScan}><Sparkles/>Scan now</button></div>}
function MonitorList({monitors,reload,create}:{monitors:Monitor[];reload:()=>void;create:()=>void}){const toggle=async(id:string,e:boolean)=>{await fetch('/api/monitors/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:e})});reload()};const remove=async(id:string)=>{if(!confirm('Delete this monitor?'))return;await fetch('/api/monitors/'+id,{method:'DELETE'});reload()};return <div className="monitorGrid">{monitors.map(m=><article className="monitor"key={m.id}><div className="monitorHeader"><div className="monitorStatus"><span className={m.enabled?'on':'off'}></span>{m.enabled?'Monitoring':'Paused'}</div><div className="monitorActions"><button className="iconBtn"onClick={()=>toggle(m.id,!m.enabled)}>{m.enabled?<><Pause/>Pause</>:<><Play/>Play</>}</button><button className="deleteBtn"onClick={()=>remove(m.id)}><Trash2/></button></div></div><h2>{m.name}</h2><p>{m.description||'Keyword-based Reddit monitor.'}</p><RuleSummary m={m}/><div className="monitorMeta">Alert ≥ {m.threshold}%<ChevronRight/></div></article>)}<button className="newMonitor"onClick={create}><Plus/><b>Create another monitor</b><span>AND · OR · NOT Reddit listening</span></button></div>}
function RuleSummary({m}:{m:Monitor}){return <div className="ruleSummary">{m.all.length>0&&<span><b>AND</b> {m.all.map(x=>x.value).join(', ')}</span>}{m.any.length>0&&<span><b>OR</b> {m.any.map(x=>x.value).join(', ')}</span>}{m.exclude.length>0&&<span><b>NOT</b> {m.exclude.map(x=>x.value).join(', ')}</span>}{m.subreddits.includes('all')?<span>All Reddit</span>:<span>{m.subreddits.map(s=>'r/'+s).join(', ')}</span>}</div>}
function SettingsPanel({data,reload}:{data:Data;reload:()=>void}){const[slack,setSlack]=useState('');const save=async()=>{await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slackWebhook:slack})});setSlack('');reload()};return <div className="settingsCard"><div className="settingRow"><div><h2>Reddit monitoring</h2><p>Global Reddit search via public RSS. No Reddit account or API credentials required.</p></div><span className="connected">Connected</span></div><div className="divider"/><div className="settingRow"><div><h2>Slack alerts</h2><p>Send matched conversations to a Slack channel with an incoming webhook.</p></div><span className={data.settings.slackConfigured?'connected':'notConnected'}>{data.settings.slackConfigured?'Connected':'Not connected'}</span></div><div className="slackForm"><input type="password"placeholder="Paste Slack webhook URL"value={slack}onChange={e=>setSlack(e.target.value)}/><button className="primary"disabled={!slack}onClick={save}>Save webhook</button></div><div className="security"><ShieldCheck/>Credentials are kept server-side and are never returned by the API.</div></div>}
function CreateModal({close,created}:{close:()=>void;created:()=>void}){const[name,setName]=useState('');const[description,setDescription]=useState('');const[rules,setRules]=useState(emptyRules());const[subs,setSubs]=useState('all');const[threshold,setThreshold]=useState(60);const[saving,setSaving]=useState(false);const add=(mode:RuleMode)=>setRules(r=>({...r,[mode]:[...r[mode],{id:crypto.randomUUID(),value:''}]}));const update=(mode:RuleMode,id:string,value:string)=>setRules(r=>({...r,[mode]:r[mode].map(x=>x.id===id?{...x,value}:x)}));const remove=(mode:RuleMode,id:string)=>setRules(r=>({...r,[mode]:r[mode].filter(x=>x.id!==id)}));const save=async()=>{const clean=(v:Rule[])=>v.map(x=>x.value.trim()).filter(Boolean);if(!name.trim()||(!clean(rules.all).length&&!clean(rules.any).length))return;setSaving(true);const r=await fetch('/api/monitors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description,all:clean(rules.all),any:clean(rules.any),exclude:clean(rules.exclude),subreddits:subs.split(',').map(x=>x.trim()).filter(Boolean),threshold})});if(r.ok)created();else setSaving(false)};return <div className="overlay"><div className="modal"><button className="close"onClick={close}><X/></button><p className="eyebrow">NEW MONITOR</p><h2>Listen for what matters</h2><p className="modalSub">Build the same kind of Boolean logic you use in Syften: AND, OR and NOT.</p><label>Monitor name<input value={name}onChange={e=>setName(e.target.value)}placeholder="e.g. CallRail complaints"/></label><label>Description<input value={description}onChange={e=>setDescription(e.target.value)}placeholder="What do you want to catch?"/></label><RuleGroup title="Match ALL of these"mode="all"rules={rules.all}add={add}update={update}remove={remove}placeholder="e.g. google ads"/><RuleGroup title="Match ANY of these"mode="any"rules={rules.any}add={add}update={update}remove={remove}placeholder="e.g. call tracking"/><RuleGroup title="Exclude ANY of these"mode="exclude"rules={rules.exclude}add={add}update={update}remove={remove}placeholder="e.g. telemarketing"/><label>Subreddits <small>comma separated · use all for global Reddit</small><input value={subs}onChange={e=>setSubs(e.target.value)}placeholder="all, PPC, marketing"/></label><label>Minimum relevance <b>{threshold}%</b><input type="range"min="1"max="99"value={threshold}onChange={e=>setThreshold(+e.target.value)}/></label><div className="modalActions"><button onClick={close}>Cancel</button><button className="primary"disabled={!name.trim()||(!rules.all.length&&!rules.any.length)||saving}onClick={save}>{saving?'Creating…':'Create monitor'}</button></div></div></div>}
function RuleGroup({title,mode,rules,add,update,remove,placeholder}:{title:string;mode:RuleMode;rules:Rule[];add:(m:RuleMode)=>void;update:(m:RuleMode,id:string,v:string)=>void;remove:(m:RuleMode,id:string)=>void;placeholder:string}){return <div className="ruleGroup"><div className="ruleTitle"><span>{title}</span><button type="button"onClick={()=>add(mode)}><Plus/>Add</button></div>{rules.map(r=><div className="ruleRow"key={r.id}><input value={r.value}onChange={e=>update(mode,r.id,e.target.value)}placeholder={placeholder}/><button type="button"onClick={()=>remove(mode,r.id)}><X/></button></div>)}{!rules.length&&<div className="ruleEmpty">No rules added</div>}</div>}
function ago(d:string){const s=Math.max(0,Math.floor((Date.now()-new Date(d).getTime())/1000));if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';if(s<86400)return Math.floor(s/3600)+'h ago';return Math.floor(s/86400)+'d ago'}

createRoot(document.getElementById('root')!).render(<App/>);
